<?php require '../app/Views/header.phtml' ?>
<h1>Registration Page</h1>

<form class="signup-form" action="../Registration/iii" method="POST">
    <input type="text" name="firstname" placeholder="Firstname">
    <input type="text" name="lastname" placeholder="Lastname">
    <input type="text" name="email" placeholder="E-mail">
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="pwd" placeholder="Password">
    <input type="password" name="pwd-repeat" placeholder="Repeat password">
    <button type="submit" name="signup-submit">Sign up</button>
</form>