<?php require '../app/Views/header.phtml' ?>

<h1>Gallery Page</h1>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-image">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Description</th>
                        <th scope="col">Title</th>
                        <th scope="col">Uploader</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(isset($gallery)) foreach ($gallery as $key => $value): ?>
                    <tr>
                        <th scope="row"><?php echo $key; ?></th>
                        <td class="w-25">
                            <img src="<?php echo '/img/' . $value->imgFullNameGallery ?>" class="img-fluid img-thumbnail" alt="Image">
                        </td>
                        <td><?php echo $value->descGallery; ?></td>
                        <td><?php echo $value->titleGallery; ?></td>
                        <td><?php echo '<a href="/Gallery/user/'. $value->uploader .'">'. $value->uploader . '</a>'; ?></td>
                        <td><?php
                            if($value->uploaderid == \Models\Session::get('id')) {
                                echo '<a href="/Gallery/delete/' . $value->uploaderid . '/'. $value->imgFullNameGallery .'">' . 'Delete' . '</a>';
                            }
                            ?>

                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<?php require '../app/Views/footer.phtml' ?>