<?php require '../app/Views/header.phtml' ?>

    <h1>Gallery Page</h1>


    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-image">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Description</th>
                        <th scope="col">Title</th>
                        <th scope="col">Uploader</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <?php
                        if (isset($success))
                            echo '<div class="alert alert-success" role="alert">' . $success . '</div>';

                        if (empty($gallery))
                            echo '<div class="alert alert-dark" role="alert">There are no images yet. Please go to the profile page and upload an image.</div>';

                        if (isset($gallery))
                        foreach ($gallery

                        as $key => $value): ?>
                        <th scope="row"><?php echo $key; ?></th>
                        <td class="w-25">
                            <img src="<?php echo '/img/' . $value->imgFullNameGallery ?>"
                                 class="img-fluid img-thumbnail" alt="Image">
                        </td>
                        <?php if ($value->uploaderid == \Models\Session::get('id')): ?>
                            <td><?php echo '<textarea cols="30" rows="5" id="tabletext" type="textarea"">' . $value->descGallery . '</textarea>'; ?></td>
                            <td><?php echo '<input id="tabletext" value="' . $value->titleGallery . '">'; ?></td>
                            <p id="id" hidden><?php echo $value->id ?></p>
                        <?php endif; ?>

                        <?php if ($value->uploaderid !== \Models\Session::get('id')): ?>
                            <td><?php echo $value->descGallery?></td>
                            <td><?php echo $value->titleGallery?></td>
                        <?php endif; ?>

                        <td><?php echo '<a href="/Gallery/user/' . $value->uploader . '">' . $value->uploader . '</a>'; ?></td>
                        <td><?php
                            if ($value->uploaderid == \Models\Session::get('id')) {
                                echo '<input type="submit" id="update-row-submit" value="Update" title="Show the number of images">';
                                echo '<div id="upd"></div>';
                                echo '<a href="/Gallery/delete/' . $value->id . '/' . $value->imgFullNameGallery . '">' . 'Delete' . '</a>';
                            }
                            ?>

                        </td>
                    </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

<?php require '../app/Views/footer.phtml' ?>