<?php
\Models\Session::start();
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="/style.css" rel="stylesheet" media="all">
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav>
    <ul>
        <li><a href="/Home/">Home</a></li>
        <?php if (!\Models\Session::get('id')): ?>
            <li><a href="/Login/">Login</a></li>
            <li><a href="/Registration/">Registration</a></li>
        <?php endif; ?>
        <?php if (\Models\Session::get('id')): ?>
            <li><a href="/Gallery/">Gallery</a></li>
            <li><a href="/Profile/">Profile</a></li>
            <li><a href="/Logout/logout">Logout</a></li>
        <?php endif; ?>
    </ul>
</nav>