<?php
if(!isset($_SESSION))
{
    session_start();
}
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link href="/style.css" rel = "stylesheet" media = "all">
</head>
<body>
<nav>
    <ul>
        <li> <a href = "/Home/">Homepage</a> </li>
        <?php if(!isset($_SESSION['id'])): ?>
        <li> <a href = "/Login/">Login</a> </li>
        <li> <a href = "/Registration/">Registration</a> </li>
        <?php endif; ?>
        <?php if(isset($_SESSION['id'])): ?>
        <li> <a href = "/Registration/">Gallery</a> </li>
        <li> <a href = "/Registration/">Management</a> </li>
        <li> <a href = "/Registration/">Profile</a> </li>
        <li> <a href = "/Logout/logout">Logout</a> </li>
        <?php endif; ?>
    </ul>
</nav>